# Generated by Django 4.2.27 on 2026-02-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_entrypass_delete_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrypass',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
